### ISSUE TITLE
Please enable discussions

### ISSUE THREAD

**Issue by unicomp21** [Blimster/kafka_protocol#1]
Hi @Blimster 

Are there any tests around this?  Or some way I can verify it?  The reason for asking, I've started work on a concept which could potentially be used as a replacement for avro.  Still pretty rough, but I need kafka support from dart.  Originally, I was thinking of interop w/ kafkajs, but this would be way better I think.

In addition, for automated testing while working on this feature, the lib could be really useful.
https://github.com/vectorizedio/redpanda/issues/1667#issuecomment-877130993

Oh, also, if possible, please enable discussions on this repo and babylon_dart.  This will keep me from polluting issues w/ non-feature related chatter.

Thanks!

**Comment by Blimster** [comment]
Discussions feature is enabled now. I enabled it for babylon_dart already last week. I will close this issue. Please, post your topic as a discussion again.
