### ISSUE TITLE
generating kafka message code

### ISSUE THREAD

**Issue by unicomp21** [Blimster/kafka_protocol#2]
I'm guessing we could use these json files to generate the rest of the code?

https://github.com/apache/kafka/tree/d3709dafbe4d77e0635d3a39bbb9a4f14be159bf/clients/src/main/resources/common/message

Templating options for code generation, is see options like:
https://pub.dev/packages/mustache_template
https://pub.dev/packages/simple_mustache
https://pub.dev/packages/jinja

**Comment by Blimster** [comment]
Lets move this topic to discussions. I close this issue.
